/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UniFlag {
        "name": string;
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagCn {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagDe {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagEs {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagFr {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagGb {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagIt {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagJp {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagKr {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagPt {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagRu {
        "round": boolean;
        "square": boolean;
    }
    interface UniFlagUs {
        "round": boolean;
        "square": boolean;
    }
}
declare global {
    interface HTMLUniFlagElement extends Components.UniFlag, HTMLStencilElement {
    }
    var HTMLUniFlagElement: {
        prototype: HTMLUniFlagElement;
        new (): HTMLUniFlagElement;
    };
    interface HTMLUniFlagCnElement extends Components.UniFlagCn, HTMLStencilElement {
    }
    var HTMLUniFlagCnElement: {
        prototype: HTMLUniFlagCnElement;
        new (): HTMLUniFlagCnElement;
    };
    interface HTMLUniFlagDeElement extends Components.UniFlagDe, HTMLStencilElement {
    }
    var HTMLUniFlagDeElement: {
        prototype: HTMLUniFlagDeElement;
        new (): HTMLUniFlagDeElement;
    };
    interface HTMLUniFlagEsElement extends Components.UniFlagEs, HTMLStencilElement {
    }
    var HTMLUniFlagEsElement: {
        prototype: HTMLUniFlagEsElement;
        new (): HTMLUniFlagEsElement;
    };
    interface HTMLUniFlagFrElement extends Components.UniFlagFr, HTMLStencilElement {
    }
    var HTMLUniFlagFrElement: {
        prototype: HTMLUniFlagFrElement;
        new (): HTMLUniFlagFrElement;
    };
    interface HTMLUniFlagGbElement extends Components.UniFlagGb, HTMLStencilElement {
    }
    var HTMLUniFlagGbElement: {
        prototype: HTMLUniFlagGbElement;
        new (): HTMLUniFlagGbElement;
    };
    interface HTMLUniFlagItElement extends Components.UniFlagIt, HTMLStencilElement {
    }
    var HTMLUniFlagItElement: {
        prototype: HTMLUniFlagItElement;
        new (): HTMLUniFlagItElement;
    };
    interface HTMLUniFlagJpElement extends Components.UniFlagJp, HTMLStencilElement {
    }
    var HTMLUniFlagJpElement: {
        prototype: HTMLUniFlagJpElement;
        new (): HTMLUniFlagJpElement;
    };
    interface HTMLUniFlagKrElement extends Components.UniFlagKr, HTMLStencilElement {
    }
    var HTMLUniFlagKrElement: {
        prototype: HTMLUniFlagKrElement;
        new (): HTMLUniFlagKrElement;
    };
    interface HTMLUniFlagPtElement extends Components.UniFlagPt, HTMLStencilElement {
    }
    var HTMLUniFlagPtElement: {
        prototype: HTMLUniFlagPtElement;
        new (): HTMLUniFlagPtElement;
    };
    interface HTMLUniFlagRuElement extends Components.UniFlagRu, HTMLStencilElement {
    }
    var HTMLUniFlagRuElement: {
        prototype: HTMLUniFlagRuElement;
        new (): HTMLUniFlagRuElement;
    };
    interface HTMLUniFlagUsElement extends Components.UniFlagUs, HTMLStencilElement {
    }
    var HTMLUniFlagUsElement: {
        prototype: HTMLUniFlagUsElement;
        new (): HTMLUniFlagUsElement;
    };
    interface HTMLElementTagNameMap {
        "uni-flag": HTMLUniFlagElement;
        "uni-flag-cn": HTMLUniFlagCnElement;
        "uni-flag-de": HTMLUniFlagDeElement;
        "uni-flag-es": HTMLUniFlagEsElement;
        "uni-flag-fr": HTMLUniFlagFrElement;
        "uni-flag-gb": HTMLUniFlagGbElement;
        "uni-flag-it": HTMLUniFlagItElement;
        "uni-flag-jp": HTMLUniFlagJpElement;
        "uni-flag-kr": HTMLUniFlagKrElement;
        "uni-flag-pt": HTMLUniFlagPtElement;
        "uni-flag-ru": HTMLUniFlagRuElement;
        "uni-flag-us": HTMLUniFlagUsElement;
    }
}
declare namespace LocalJSX {
    interface UniFlag {
        "name"?: string;
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagCn {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagDe {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagEs {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagFr {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagGb {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagIt {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagJp {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagKr {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagPt {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagRu {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface UniFlagUs {
        "round"?: boolean;
        "square"?: boolean;
    }
    interface IntrinsicElements {
        "uni-flag": UniFlag;
        "uni-flag-cn": UniFlagCn;
        "uni-flag-de": UniFlagDe;
        "uni-flag-es": UniFlagEs;
        "uni-flag-fr": UniFlagFr;
        "uni-flag-gb": UniFlagGb;
        "uni-flag-it": UniFlagIt;
        "uni-flag-jp": UniFlagJp;
        "uni-flag-kr": UniFlagKr;
        "uni-flag-pt": UniFlagPt;
        "uni-flag-ru": UniFlagRu;
        "uni-flag-us": UniFlagUs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uni-flag": LocalJSX.UniFlag & JSXBase.HTMLAttributes<HTMLUniFlagElement>;
            "uni-flag-cn": LocalJSX.UniFlagCn & JSXBase.HTMLAttributes<HTMLUniFlagCnElement>;
            "uni-flag-de": LocalJSX.UniFlagDe & JSXBase.HTMLAttributes<HTMLUniFlagDeElement>;
            "uni-flag-es": LocalJSX.UniFlagEs & JSXBase.HTMLAttributes<HTMLUniFlagEsElement>;
            "uni-flag-fr": LocalJSX.UniFlagFr & JSXBase.HTMLAttributes<HTMLUniFlagFrElement>;
            "uni-flag-gb": LocalJSX.UniFlagGb & JSXBase.HTMLAttributes<HTMLUniFlagGbElement>;
            "uni-flag-it": LocalJSX.UniFlagIt & JSXBase.HTMLAttributes<HTMLUniFlagItElement>;
            "uni-flag-jp": LocalJSX.UniFlagJp & JSXBase.HTMLAttributes<HTMLUniFlagJpElement>;
            "uni-flag-kr": LocalJSX.UniFlagKr & JSXBase.HTMLAttributes<HTMLUniFlagKrElement>;
            "uni-flag-pt": LocalJSX.UniFlagPt & JSXBase.HTMLAttributes<HTMLUniFlagPtElement>;
            "uni-flag-ru": LocalJSX.UniFlagRu & JSXBase.HTMLAttributes<HTMLUniFlagRuElement>;
            "uni-flag-us": LocalJSX.UniFlagUs & JSXBase.HTMLAttributes<HTMLUniFlagUsElement>;
        }
    }
}
